### ISSUE TITLE
dispatcher worker cannot write to hermes-data

### ISSUE THREAD

**Issue by dmd** [hermes-router/hermes#15]
In 0.1d, the dispatcher worker runs as the user `hermes`, which means it fails writing to `hermes-data` because files are written there **as root** by the router.

```
Jan 24 18:21:00 mic-dicom-router rq[983]: 18:21:00 default: dispatch.send.execute({'target_ip': '172.29.158.176', 'target_port': '5000', 'target_aet_target':..., PosixPath('/home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231..., PosixPath('/home/hermes/hermes-data/success'), PosixPath('/home/hermes/hermes-data/error'), 5, 30, <common.monitor.Monitor object at 0x7f9a696833c8>) (aae7ec89-4d4d-4954-b32c-ce65a53a975c)
Jan 24 18:21:00 mic-dicom-router rq[983]: E: cannot write detailed report to file '/home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231464804/sent.txt'
Jan 24 18:21:00 mic-dicom-router rq[983]: Failed command:
Jan 24 18:21:00 mic-dicom-router rq[983]:  dcmsend 172.29.158.176 5000 +sd /home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231464804
Jan 24 18:21:00 mic-dicom-router rq[983]:             -aet mic-dicom-router -aec ogawatest1 -nuc
Jan 24 18:21:00 mic-dicom-router rq[983]:             +sp '*.dcm' -to 60 +crf /home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231464804/sent.txt
Jan 24 18:21:00 mic-dicom-router rq[983]: because of EXITCODE_CANNOT_WRITE_REPORT_FILE
Jan 24 18:21:00 mic-dicom-router rq[983]: Traceback (most recent call last):
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "./dispatch/send.py", line 64, in execute
Jan 24 18:21:00 mic-dicom-router rq[983]:     run(split(command), check=True)
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "/home/hermes/hermes-env/lib/python3.6/subprocess.py", line 438, in run
Jan 24 18:21:00 mic-dicom-router rq[983]:     output=stdout, stderr=stderr)
Jan 24 18:21:00 mic-dicom-router rq[983]: subprocess.CalledProcessError: Command '['dcmsend', '172.29.158.176', '5000', '+sd', '/home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231464804', '-aet', 'mic-dicom-router', '-aec', 'ogawatest1', '-nuc', '+sp', '*.dcm', '-to', '60', '+crf', '/home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231464804/sent.txt']' returned non-zero exit status 43.
Jan 24 18:21:00 mic-dicom-router rq[983]: 18:21:00 Traceback (most recent call last):
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "./dispatch/send.py", line 64, in execute
Jan 24 18:21:00 mic-dicom-router rq[983]:     run(split(command), check=True)
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "/home/hermes/hermes-env/lib/python3.6/subprocess.py", line 438, in run
Jan 24 18:21:00 mic-dicom-router rq[983]:     output=stdout, stderr=stderr)
Jan 24 18:21:00 mic-dicom-router rq[983]: subprocess.CalledProcessError: Command '['dcmsend', '172.29.158.176', '5000', '+sd', '/home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231464804', '-aet', 'mic-dicom-router', '-aec', 'ogawatest1', '-nuc', '+sp', '*.dcm', '-to', '60', '+crf', '/home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231464804/sent.txt']' returned non-zero exit status 43.
Jan 24 18:21:00 mic-dicom-router rq[983]: During handling of the above exception, another exception occurred:
Jan 24 18:21:00 mic-dicom-router rq[983]: Traceback (most recent call last):
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "/home/hermes/hermes-env/lib/python3.6/site-packages/rq/worker.py", line 975, in perform_job
Jan 24 18:21:00 mic-dicom-router rq[983]:     rv = job.perform()
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "/home/hermes/hermes-env/lib/python3.6/site-packages/rq/job.py", line 696, in perform
Jan 24 18:21:00 mic-dicom-router rq[983]:     self._result = self._execute()
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "/home/hermes/hermes-env/lib/python3.6/site-packages/rq/job.py", line 719, in _execute
Jan 24 18:21:00 mic-dicom-router rq[983]:     return self.func(*self.args, **self.kwargs)
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "./dispatch/send.py", line 78, in execute
Jan 24 18:21:00 mic-dicom-router rq[983]:     retry_increased = _increase_retry(source_folder, retry_max, retry_delay)
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "./dispatch/send.py", line 133, in _increase_retry
Jan 24 18:21:00 mic-dicom-router rq[983]:     with open(target_json_path, "w") as file:
Jan 24 18:21:00 mic-dicom-router rq[983]: PermissionError: [Errno 13] Permission denied: '/home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231464804/target.json'
Jan 24 18:21:00 mic-dicom-router rq[983]: Traceback (most recent call last):
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "./dispatch/send.py", line 64, in execute
Jan 24 18:21:00 mic-dicom-router rq[983]:     run(split(command), check=True)
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "/home/hermes/hermes-env/lib/python3.6/subprocess.py", line 438, in run
Jan 24 18:21:00 mic-dicom-router rq[983]:     output=stdout, stderr=stderr)
Jan 24 18:21:00 mic-dicom-router rq[983]: subprocess.CalledProcessError: Command '['dcmsend', '172.29.158.176', '5000', '+sd', '/home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231464804', '-aet', 'mic-dicom-router', '-aec', 'ogawatest1', '-nuc', '+sp', '*.dcm', '-to', '60', '+crf', '/home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231464804/sent.txt']' returned non-zero exit status 43.
Jan 24 18:21:00 mic-dicom-router rq[983]: During handling of the above exception, another exception occurred:
Jan 24 18:21:00 mic-dicom-router rq[983]: Traceback (most recent call last):
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "/home/hermes/hermes-env/lib/python3.6/site-packages/rq/worker.py", line 975, in perform_job
Jan 24 18:21:00 mic-dicom-router rq[983]:     rv = job.perform()
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "/home/hermes/hermes-env/lib/python3.6/site-packages/rq/job.py", line 696, in perform
Jan 24 18:21:00 mic-dicom-router rq[983]:     self._result = self._execute()
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "/home/hermes/hermes-env/lib/python3.6/site-packages/rq/job.py", line 719, in _execute
Jan 24 18:21:00 mic-dicom-router rq[983]:     return self.func(*self.args, **self.kwargs)
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "./dispatch/send.py", line 78, in execute
Jan 24 18:21:00 mic-dicom-router rq[983]:     retry_increased = _increase_retry(source_folder, retry_max, retry_delay)
Jan 24 18:21:00 mic-dicom-router rq[983]:   File "./dispatch/send.py", line 133, in _increase_retry
Jan 24 18:21:00 mic-dicom-router rq[983]:     with open(target_json_path, "w") as file:
Jan 24 18:21:00 mic-dicom-router rq[983]: PermissionError: [Errno 13] Permission denied: '/home/hermes/hermes-data/outgoing/e8765396-5e70-11eb-af07-f64231464804/target.json'
```

I'm confused as to how this could possibly be working for anyone else!

**Comment by dmd** [comment]
This can be fixed by commenting out `User=hermes` in the systemd unit, of course, but currently the shipping version definitely doesn't work.

**Comment by joshy** [comment]
Thanks for the report, I will check with the current settings and I will update accordingly.

--

**Comment by dmd** [comment]
Thanks. I'm curious how 0.1d could have worked for you before this change?

**Comment by joshy** [comment]
I didn‘t had a new installation but was using the existing installation. The directory permission where read write for all users. 

--
